# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

name: docs

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.x

      - name: Install Python packages
        run: pip install -r requirements.txt -r docs/requirements.txt

      - name: Build documentation
        run: bash -c "PYTHONPATH=$PWD mkdocs build"
